# Generated by Django 2.2 on 2019-06-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_document_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
    ]
